settings:
  gpt-api-key:
  gpt-endpoint: "https://api.openai.com/v1"
  kafka:
    topics:
      cleaned-text:
  model:
server:
  port:
spring:
  kafka:
    bootstrap-servers: "localhost:29092"
  cloud:
    function:
      definition: myConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        myConsumer-in-0:
          destination: cleaned_text
          group: group1
  data:
    mongodb:
      host: "localhost"
      port: 27017
      username: "root"
      password: "example"
      database: "cvizard"
      authentication-database: "admin"
