settings:
  gpt-api-key: ""
  gpt-endpoint: "https://api.openai.com/v1"
  kafka:
    topics:
      cleaned-text: cleaned_text
  model: "gpt-3.5-turbo"

server:
  port:
spring:
  main:
    lazy-initialization: true

  kafka:
    bootstrap-servers: "http://localhost:29092"
  cloud:
    function:
      definition: myConsumer
    stream:
      kafka:
        binder:
          brokers: "http://localhost:29092"
      bindings:
        myConsumer-in-0:
          destination: "cleaned_text"
          group: "gro"
  data:
    mongodb:
      host: "localhost"
      port: 27017
      username: "minonek"
      password: "cvizard2023"
      database: "cvizard"
      authentication-database: "admin"
