
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java_ci_with_maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  docker_build_and_push:
       runs-on: ubuntu-latest
       needs: ["java_ci_with_maven"]
       steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to Docker Registry
         uses: docker/login-action@v1
         with:
           registry: https://cvizard.com:5001
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           tags: cvizard.com:5001/pdfconverter:${{ github.sha }}
           
  deploy:
      runs-on: ubuntu-latest
      needs: ["docker_build_and_push"]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://cvizard.com:5001
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull the latest image
        run: docker pull cvizard.com:5001/pdfconverter:${{ github.sha }}

      - name: Stop and remove old container
        run: docker stop pdfconverter || true && docker rm pdfconverter || true

      - name: Start new container
        run: docker run -d --name pdfconverter -p 8080:8080 cvizard.com:5001/pdfconverter:${{ github.sha }}

